---
title: "08_SYN_MainAnalysis_AME"
output: html_document
date: "2023-02-03"
---

# 1. Load Packages
```{r}
library(brms)
library(marginaleffects)
library(tidyverse)



options(scipen = 999)

set.seed(180822)

set_priors <- c(prior(normal(0, 1), class = b),
                prior(normal(0, 1), class = sd))
```

# 2. Load Data
```{r}
load("FAKE_cccu_MA.RData")

FAKE_cccu_MA <- FAKE_cccu_MA %>%
  arrange(CASEID) %>%
  mutate_if(is.factor, droplevels)

FAKE_cccu_MA_hc_only <- FAKE_cccu_MA %>%
  filter(hc == "hc") %>%
  mutate_if(is.factor, droplevels)

FAKE_cccu_MA_nonhc_only <- FAKE_cccu_MA %>%
  filter(hc == "non_hc") %>%
  mutate_if(is.factor, droplevels)
  
```

# 3. Load models of main analysis
```{r}
FAKE_m1 <- brm(file = "models/FAKE_m1.Rds")
FAKE_m2 <- brm(file = "models/FAKE_m2.Rds")
FAKE_m2_hc_only <- brm(file = "models/FAKE_m2_hc_only.Rds")
FAKE_m2_nonhc_only <- brm(file = "models/FAKE_m2_nonhc_only.Rds")
FAKE_m3 <- brm(file = "models/FAKE_m3.Rds")
FAKE_m3_hc_only <- brm(file = "models/FAKE_m3_hc_only.Rds")
FAKE_m3_nonhc_only <- brm(file = "models/FAKE_m3_nonhc_only.Rds")
FAKE_m4 <- brm(file = "models/FAKE_m4.Rds")
FAKE_m4_hc_only <- brm(file = "models/FAKE_m4_hc_only.Rds")
FAKE_m4_nonhc_only <- brm(file = "models/FAKE_m4_nonhc_only.Rds")
```

# 4. Compute Average marginal effects

## FAKE_m1
```{r}
#average marginal effect
ame <- marginaleffects(FAKE_m1)
ame_sum <- summary(ame, conf_level = .997)
print(ame_sum, nrow = 100)
```

## FAKE_m2
```{r}
#average marginal effect
ame <- marginaleffects(FAKE_m2)
summary(ame, conf_level = .997)

ame <- marginaleffects(FAKE_m2_hc_only)
summary(ame, conf_level = .997)

ame <- marginaleffects(FAKE_m2_nonhc_only)
summary(ame, conf_level = .997)
```

## FAKE_m3
```{r}
#average marginal effect
ame <- marginaleffects(FAKE_m3)
summary(ame, conf_level = .997)


ame <- marginaleffects(FAKE_m3_hc_only)
summary(ame, conf_level = .997)



ame <- marginaleffects(FAKE_m3_nonhc_only)
summary(ame, conf_level = .997)
```

## FAKE_m4
```{r}
#model 4
ame <- marginaleffects(FAKE_m4)
ame_sum <- summary(ame, conf_level = .997)
print(ame_sum, nrow = 100000)
```


```{r}
ame <- marginaleffects(FAKE_m4_hc_only)
ame_sum <- summary(ame, conf_level = .997)
print(ame_sum, nrow = 100000)
```


```{r}
ame <- marginaleffects(FAKE_m4_nonhc_only)
ame_sum <- summary(ame, conf_level = .997)
print(ame_sum, nrow = 100000)
```