---
title: "09_SYN_MainAnalyis_Robust_Models_AME"
output: html_document
date: "2023-02-03"
---

# 1. Load Packages
```{r}
library(brms)
library(marginaleffects)
library(tidyverse)

options(scipen = 999)

set.seed(180822)

set_priors <- c(prior(normal(0, 1), class = b),
                prior(normal(0, 1), class = sd))
```

# 2. Load Data
```{r}
#MA
load("FAKE_cccu_R1.RData")

load("FAKE_cccu_R2.RData")
```


```{r}
FAKE_cccu_R1 <- FAKE_cccu_R1 %>%
  arrange(CASEID) %>%
  mutate_if(is.factor, droplevels)

FAKE_cccu_R1_hc_only <- FAKE_cccu_R1 %>%
  filter(hc == "hc") %>%
  mutate_if(is.factor, droplevels)

FAKE_cccu_R1_nonhc_only <- FAKE_cccu_R1 %>%
  filter(hc == "non_hc") %>%
  mutate_if(is.factor, droplevels)

FAKE_cccu_R2 <- FAKE_cccu_R2 %>%
  arrange(CASEID) %>%
  mutate_if(is.factor, droplevels)

FAKE_cccu_R2_hc_only <- FAKE_cccu_R2 %>%
  filter(hc == "hc") %>%
  mutate_if(is.factor, droplevels)

FAKE_cccu_R2_nonhc_only <- FAKE_cccu_R2 %>%
  filter(hc == "non_hc") %>%
  mutate_if(is.factor, droplevels)


```

# 3. Load models of main analysis
```{r}
FAKE_R1_ma_1 <- brm(file = "models/FAKE_R1_ma_1.Rds")
FAKE_R2_ma_1 <- brm(file = "models/FAKE_R2_ma_1.Rds")

FAKE_R1_ma_2 <- brm(file = "models/FAKE_R1_ma_2.Rds")
FAKE_R1_m2_hc_only <- brm(file = "models/FAKE_R1_m2_hc_only.Rds")
FAKE_R1_m2_nonhc_only <- brm(file = "models/FAKE_R1_m2_nonhc_only.Rds")
FAKE_R2_ma_2 <- brm(file = "models/FAKE_R2_ma_2.Rds")
FAKE_R2_m2_hc_only <- brm(file = "models/FAKE_R2_m2_hc_only.Rds")
FAKE_R2_m2_nonhc_only <- brm(file = "models/FAKE_R2_m2_nonhc_only.Rds")

FAKE_R1_ma_3 <- brm(file = "models/FAKE_R1_ma_3.Rds")
FAKE_R1_m3_hc_only <- brm(file = "models/FAKE_R1_m3_hc_only.Rds")
FAKE_R1_m3_nonhc_only <- brm(file = "models/FAKE_R1_m3_nonhc_only.Rds")
FAKE_R2_ma_3 <- brm(file = "models/FAKE_R2_ma_3.Rds")
FAKE_R2_m3_hc_only <- brm(file = "models/FAKE_R2_m3_hc_only.Rds")
FAKE_R2_m3_nonhc_only <- brm(file = "models/FAKE_R2_m3_nonhc_only.Rds")

FAKE_R1_ma_4 <- brm(file = "models/FAKE_R1_ma_4.Rds")
FAKE_R1_m4_hc_only <- brm(file = "models/FAKE_R1_m4_hc_only.Rds")
FAKE_R1_m4_nonhc_only <- brm(file = "models/FAKE_R1_m4_nonhc_only.Rds")
FAKE_R2_ma_4 <- brm(file = "models/FAKE_R2_ma_4.Rds")
FAKE_R2_m4_hc_only<- brm(file = "models/FAKE_R2_m4_hc_only.Rds")
FAKE_R2_m4_nonhc_only <- brm(file = "models/FAKE_R2_m4_nonhc_only.Rds")
```

# 4. Average marginal effects for models in main analyses for robustness analyses

## Model1
### R1
```{r}

#average marginal effect
ame <- marginaleffects(FAKE_R1_ma_1)
summary(ame, conf_level = .997)


```

### R2
```{r}
#average marginal effect
ame <- marginaleffects(FAKE_R2_ma_1)
summary(ame, conf_level = .997)


```


## Model 2
### R1
```{r}
#average marginal effect
ame <- marginaleffects(FAKE_R1_ma_2)
summary(ame, conf_level = .997)

ame <- marginaleffects(FAKE_R1_m2_hc_only)
summary(ame, conf_level = .997)

ame <- marginaleffects(FAKE_R1_m2_nonhc_only)
summary(ame, conf_level = .997)
```

### R2
```{r}
#average marginal effect
ame <- marginaleffects(FAKE_R2_ma_2)
summary(ame, conf_level = .997)

ame <- marginaleffects(FAKE_R2_m2_hc_only)
summary(ame, conf_level = .997)

ame <- marginaleffects(FAKE_R2_m2_nonhc_only)
summary(ame, conf_level = .997)
```


## Model 3

### R1

```{r}
#average marginal effect
ame <- marginaleffects(FAKE_R1_ma_3)
summary(ame, conf_level = .997)


ame <- marginaleffects(FAKE_R1_m3_hc_only)
summary(ame, conf_level = .997)


ame <- marginaleffects(FAKE_R1_m3_nonhc_only)
summary(ame, conf_level = .997)
```



### R2
```{r}
#average marginal effect
ame <- marginaleffects(FAKE_R2_ma_3)
summary(ame, conf_level = .997)


ame <- marginaleffects(FAKE_R2_m3_hc_only)
summary(ame, conf_level = .997)


ame <- marginaleffects(FAKE_R2_m3_nonhc_only)
summary(ame, conf_level = .997)
```


## Model 4
### R1
```{r}
ame <- marginaleffects(FAKE_R1_ma_4)
ame_sum <- summary(ame, conf_level = .997)
print(ame_sum, nrow = 100000)



ame <- marginaleffects(FAKE_R1_m4_hc_only)
ame_sum <- summary(ame, conf_level = .997)
print(ame_sum, nrow = 100000)


ame <- marginaleffects(FAKE_R1_m4_nonhc_only)
ame_sum <- summary(ame, conf_level = .997)
print(ame_sum, nrow = 100000)


```

### R2
```{r}
#average marginal effect
ame <- marginaleffects(FAKE_R2_ma_4)
ame_sum <- summary(ame, conf_level = .997)
print(ame_sum, nrow = 100000)



ame <- marginaleffects(FAKE_R2_m4_hc_only)
ame_sum <- summary(ame, conf_level = .997)
print(ame_sum, nrow = 100000)




ame <- marginaleffects(FAKE_R2_m4_nonhc_only)
ame_sum <- summary(ame, conf_level = .997)
print(ame_sum, nrow = 100000)


```

