---
title: "14_SYN_SubAnalysis_Robust_Models_AME"
output: html_document
date: "2023-02-03"
---

# 1. Load Packages
```{r}
library(brms)
library(marginaleffects)
library(tidyverse)


options(scipen = 999)

set.seed(180822)

set_priors <- c(prior(normal(0, 1), class = b),
                prior(normal(0, 1), class = sd))
```

# 2. Load Data
```{r}
#SA
load("FAKE_cccu_R1_s.RData")
load("FAKE_cccu_R2_s.RData")
```

```{r}

FAKE_cccu_R1_s <- FAKE_cccu_R1_s %>%
  arrange(CASEID) %>%
  mutate_if(is.factor, droplevels)

FAKE_cccu_R2_s <- FAKE_cccu_R2_s %>%
  arrange(CASEID) %>%
  mutate_if(is.factor, droplevels)
```


# 3. Load models of robustness analysis
```{r}
FAKE_R1_sam2 <- brm(file = "models/FAKE_R1_sam2.Rds")
FAKE_R2_sam2 <- brm(file = "models/FAKE_R2_sam2.Rds")

FAKE_R1_sam3 <- brm(file = "models/FAKE_R1_sam3.Rds")
FAKE_R2_sam3 <- brm(file = "models/FAKE_R2_sam3.Rds")

FAKE_R1_sam4 <- brm(file = "models/FAKE_R1_sam4.Rds")
FAKE_R2_sam4 <- brm(file = "models/FAKE_R2_sam4.Rds")
```



# 4. Average marginal effects for models of sub analyses in robustnessanalyses

## Model 2

### R1
```{r}
#average marginal effect
ame <- marginaleffects(FAKE_R1_sam2)
summary(ame, conf_level = .997)
```


### R2
```{r}
#average marginal effect
ame <- marginaleffects(FAKE_R2_sam2)
summary(ame, conf_level = .997)
```


## Model 3
### R1
```{r}
#average marginal effect
ame <- marginaleffects(FAKE_R1_sam3)
summary(ame, conf_level = .997)
```


### R2
```{r}
#average marginal effect
ame <- marginaleffects(FAKE_R2_sam3)
summary(ame, conf_level = .997)
```

## Model 4
### R1
```{r}
#average marginal effect
ame <- marginaleffects(FAKE_R1_sam4)
ame_sum <- summary(ame, conf_level = .997)
print(ame_sum, nrow = 100000)

```


### R2
```{r}
#average marginal effect
ame <- marginaleffects(FAKE_R2_sam4)
ame_sum <- summary(ame, conf_level = .997)
print(ame_sum, nrow = 100000)

```




