---
title: "00_syndata"
output: html_document
---

# Library
```{r}
library(synthpop)
library(labelled)
library(tidyverse)
set.seed(20122021)
```

# Loading Data
```{r}
load("01_RData/DS0001/37067-0001-Data.rda")
cccu_wave1 = da37067.0001

load("01_RData/DS0002/37067-0002-Data.rda")
cccu_wave2 = da37067.0002

load("01_RData/DS0003/37067-0003-Data.rda")
cccu_wave3 = da37067.0003

load("01_RData/DS0004/37067-0004-Data.rda")
cccu_wave4 = da37067.0004
```

# Simulate
## Wave 1
```{r}
FAKE_cccu_wave1 = syn(data = cccu_wave1,
                      method = "sample")

# case id is not unique:
FAKE_cccu_wave1$syn = FAKE_cccu_wave1$syn %>%
  arrange(CASEID)
FAKE_cccu_wave1$syn$CASEID = cccu_wave1$CASEID
FAKE_cccu_wave1_df = FAKE_cccu_wave1$syn
```

## Wave 2
```{r}
FAKE_cccu_wave2 = syn(data = cccu_wave2,
                      method = "sample")

# case id is not unique:
FAKE_cccu_wave2$syn = FAKE_cccu_wave2$syn %>%
  arrange(CASEID)
FAKE_cccu_wave2$syn$CASEID = cccu_wave2$CASEID
FAKE_cccu_wave2_df = FAKE_cccu_wave2$syn
```

## Wave 3
```{r}
FAKE_cccu_wave3 = syn(data = cccu_wave3,
                      method = "sample")

# case id is not unique:
FAKE_cccu_wave3$syn = FAKE_cccu_wave3$syn %>%
  arrange(CASEID)
FAKE_cccu_wave3$syn$CASEID = cccu_wave3$CASEID
FAKE_cccu_wave3_df = FAKE_cccu_wave3$syn
```

## Wave 4
```{r}
FAKE_cccu_wave4 = syn(data = cccu_wave4,
                      method = "sample")

# case id is not unique:
FAKE_cccu_wave4$syn = FAKE_cccu_wave4$syn %>%
  arrange(CASEID)
FAKE_cccu_wave4$syn$CASEID = cccu_wave4$CASEID
FAKE_cccu_wave4_df = FAKE_cccu_wave4$syn
```

# Inspect data
```{r}
table(cccu_wave1$CPUSE)
table(FAKE_cccu_wave1_df$CPUSE)

cor.test(as.numeric(cccu_wave1$FEELPG),
         as.numeric(cccu_wave1$AVOID))

cor.test(as.numeric(FAKE_cccu_wave1_df$FEELPG),
         as.numeric(FAKE_cccu_wave1_df$AVOID))
```

# Save sim data
```{r}
save(FAKE_cccu_wave1_df, FAKE_cccu_wave2_df,
     FAKE_cccu_wave3_df, FAKE_cccu_wave4_df,
     file = "FAKE_cccu.RData")

load("FAKE_cccu.RData")
```

