---
title: "03_Exclusion"
author: "Chiara Draxler"
date: "21 1 2022"
output: html_document
---

#1. Load Data
```{r}

load("Fake_cccu_complete1.RData")
```

#2. Load Packages

```{r}
library(dplyr)
```

#3. Create Columns that indicate if person has to be excluded for every exclusion criteria 

##3.1 Exclusion: Had IUD

Create column that indicates if Vpn had used IUD (yes / no) 
```{r}
#overview 
table(Fake_cccu_complete1$IUD)

Fake_cccu_complete1 <- Fake_cccu_complete1 %>%
  mutate(exclusion_had_IUD = ifelse(IUD == "(1) Yes",1,0)) 

table(Fake_cccu_complete1$exclusion_had_IUD)

#factorize
Fake_cccu_complete1$exclusion_had_IUD<-factor(Fake_cccu_complete1$exclusion_had_IUD, levels = c(0,1), labels = c("No", "Yes"))


plot(Fake_cccu_complete1$exclusion_had_IUD)

```


## 3.2 Used Vasectomy as contraceptive method
```{r}
#overview

table(Fake_cccu_complete1$VASECTOMY)
table(Fake_cccu_complete1$SP1VAS)
table(Fake_cccu_complete1$SP2VAS)


#create column that indicates if used Vasectomy

Fake_cccu_complete1 <- Fake_cccu_complete1 %>%
  mutate(exclusion_used_vasectomy = ifelse(VASECTOMY == "(1) Yes" |
                                             SP1VAS == "(1) Yes"|
                                             SP2VAS == "(1) Yes",1,0))


table(Fake_cccu_complete1$exclusion_used_vasectomy)

#factorize and plot

Fake_cccu_complete1$exclusion_used_vasectomy<-factor(Fake_cccu_complete1$exclusion_used_vasectomy, levels = c(0,1), labels = c("No", "Yes"))


plot(Fake_cccu_complete1$exclusion_used_vasectomy)

```


#4 Exclude


#5. Save data 