---
title: "04_Codebook"
author: "Chiara Draxler"
date: "31 5 2022"
output: html_document
---

# Codebook {.tabset}
## 1. Packages and df
```{r}
library(ggplot2)
theme_set(theme_bw())
library(codebook)
library(tidyverse)
library(future)
library(Hmisc)
load("cccu_MA.RData")
```

## 2. Select data
```{r}
cccu_MA = cccu_MA %>%
  select(WAVE, switch, hc, contra_satis, hc_dur, sexual_satisfaction, sex_freq,
         AGE, DEGREE_recode, POVRATE, HLTHPROB_recode, MEDPROB_recode, GAPINS_recode, TYPEINS_recode, NKIDS_t1, pregnant_between_waves, had_baby_between_waves, Avoid_r, FEELPG_recode, rel_dur_factor)
```

## 3. Codebook
```{r}
codebook(cccu_MA, missingness_report = FALSE, indent = "###")
```



#Plots


#Correlations

```{r}
#for t1
cccu_MA_t1 <- cccu_MA%>%
  filter(WAVE == "t1")
cccu_MA_t1_correlations <- cccu_MA_t1 %>%
  select(contra_satis, hc_dur,
    sexual_satisfaction,
    AGE, POVRATE, Avoid_r, FEELPG_recode)

rcorr(as.matrix(cccu_MA_t1_correlations))


#for t2
cccu_MA_t2 <- cccu_MA%>%
  filter(WAVE == "t2")

cccu_MA_t2_correlations <- cccu_MA_t2 %>%
  select(contra_satis, hc_dur,
    sexual_satisfaction,
    AGE, POVRATE, Avoid_r, FEELPG_recode)

rcorr(as.matrix(cccu_MA_t2_correlations))

#for t3
cccu_MA_t3 <- cccu_MA%>%
  filter(WAVE == "t3")

cccu_MA_t3_correlations <- cccu_MA_t3 %>%
  select(contra_satis, hc_dur,
    sexual_satisfaction,
    AGE, POVRATE, Avoid_r, FEELPG_recode)

rcorr(as.matrix(cccu_MA_t3_correlations))
```

