---
title: "06.1_MainAnalysis_Bayesian"
author: "Chiara Draxler & Laura Botzet"
date: "18 08 2022"
output: html_document
---


# 1. Load Packages
```{r}
library(brms)
library(marginaleffects)
library(tidyverse)


options(scipen = 999)

set_priors <- c(prior(normal(0, 1), class = b),
                prior(normal(0, 1), class = sd))
```

# 2. Load Data
```{r}
load("cccu_MA.RData")

cccu_MA <- cccu_MA %>%
  arrange(CASEID)
```

# 3. Models

## 3.1 Model 1: basic model
```{r}
m1 <- brm(switch ~ hc + (1 | CASEID),
          family = bernoulli(),
          data = cccu_MA,
          prior = set_priors,
          file = "models/m1.Rds")

summary(m1, prob = .997)
```


## 3.2 Model 2: including directly with contraceptive method associated predictors
```{r}
m2 <- brm(switch ~ hc * contra_satis + (1 | CASEID),
          family = bernoulli(),
          data = cccu_MA,
          prior = set_priors,
          file = "models/m2.Rds")

summary(m2, prob = .997)
```


## 3.3 Model 3: including not directly with contraceptive method associated predictors
```{r}
m3 <-
  brm(
    switch ~ hc * contra_satis +  hc * sexual_satisfaction + hc * sex_freq + (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA,
    prior = set_priors,
    file = "models/m3.Rds"
  )

summary(m3, prob = .997)

m3_sexual_satisfaction <-
  brm(
    switch ~  hc * sexual_satisfaction  + (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA,
    prior = set_priors,
    file = "models/m3_sexual_satisfaction.Rds"
  )

summary(m3_sexual_satisfaction, prob = .997)

m3_sex_freq <-
  brm(
    switch ~  hc * sex_freq  + (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA,
    prior = set_priors,
    file = "models/m3_sex_freq.Rds"
  )

summary(m3_sex_freq, prob = .997)
```

## 3.4 Model 4: Controlling for observed selection effects
```{r}
m4 <-
  brm(
    switch ~ hc * contra_satis +  hc * sexual_satisfaction + hc * sex_freq +
      hc * AGE + hc * DEGREE_recode +
      hc * POVRATE +
      hc * HLTHPROB_recode + hc * MEDPROB_recode +  hc * GAPINS_recode +
      hc * TYPEINS_recode + hc * NKIDS_t1 +  hc * pregnant_between_waves +
      hc * had_baby_between_waves + hc * Avoid_r +
      hc * FEELPG_recode +
      hc * rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA,
    prior = set_priors,
    file = "models/m4.Rds"
  )

summary(m4, prob = .997)
```



# 4. Average marginal effects

## m1
```{r}
#average marginal effect
ame <- marginaleffects(m1)
summary(ame, conf_level = .997)
```

## m2
```{r}
#average marginal effect
ame <- marginaleffects(m2)
summary(ame, conf_level = .997)

m2_hc_only <- brm(
  switch ~ contra_satis + (1 | CASEID),
  family = bernoulli(),
  data = cccu_MA %>% filter(hc == "hc"),
  prior = set_priors,
  file = "models/m2_hc_only.Rds"
)
ame <- marginaleffects(m2_hc_only)
summary(ame, conf_level = .997)

m2_nonhc_only <- brm(
  switch ~ contra_satis + (1 | CASEID),
  family = bernoulli(),
  data = cccu_MA %>% filter(hc == "non_hc"),
  prior = set_priors,
  file = "models/m2_nonhc_only.Rds"
)
ame <- marginaleffects(m2_nonhc_only)
summary(ame, conf_level = .997)
```

## m3
```{r}
#average marginal effect
ame <- marginaleffects(m3)
summary(ame, conf_level = .997)

m3_hc_only <-
  brm(
    switch ~ contra_satis + sexual_satisfaction + sex_freq +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA %>% filter(hc == "hc"),
  prior = set_priors,
  file = "models/m3_hc_only.Rds"
  )
ame <- marginaleffects(m3_hc_only)
summary(ame, conf_level = .997)


m3_nonhc_only <-
  brm(
    switch ~ contra_satis + sexual_satisfaction + sex_freq +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA %>% filter(hc == "non_hc"),
  prior = set_priors,
  file = "models/m3_nonhc_only.Rds"
  )
ame <- marginaleffects(m3_nonhc_only)
summary(ame, conf_level = .997)
```

## m4
```{r}
#model 4
ame <- marginaleffects(m4)
summary(ame, conf_level = .997)

m4_hc_only <-
  brm(
    switch ~ contra_satis + sexual_satisfaction +  sex_freq +
      AGE + DEGREE_recode + POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r + FEELPG_recode +
      rel_dur_factor + (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA %>% filter(hc == "hc"),
  prior = set_priors,
  file = "models/m4_hc_only.Rds"
  )

ame <- marginaleffects(m4_hc_only)
summary(ame, conf_level = .997)

m4_nonhc_only <-
  brm(
    switch ~ contra_satis + sexual_satisfaction +  sex_freq +
      AGE + DEGREE_recode + POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r + FEELPG_recode +
      rel_dur_factor + (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA %>% filter(hc == "non_hc"),
  prior = set_priors,
  file = "models/m4_nonhc_only.Rds"
  )

ame <- marginaleffects(m4_nonhc_only)
summary(ame, conf_level = .997)
```

