---
title: "06.1_MainAnalysis_Bayesian"
author: "Chiara Draxler & Laura Botzet"
date: "18 08 2022"
output: html_document
---


# 1. Load Packages
```{r}
library(brms)
library(marginaleffects)
library(tidyverse)


options(scipen = 999)

set.seed(180822)

set_priors <- c(prior(normal(0, 1), class = b),
                prior(normal(0, 1), class = sd))
```

# 2. Load Data
```{r}
load("cccu_MA.RData")

cccu_MA <- cccu_MA %>%
  arrange(CASEID)
```

# 3. Models

## 3.1 Model 1: basic model
```{r}
m1 <- brm(switch ~ hc + (1 | CASEID),
          family = bernoulli(),
          data = cccu_MA,
          prior = set_priors,
          file = "models/m1.Rds")

summary(m1, prob = .997)
```


## 3.2 Model 2: including directly with contraceptive method associated predictors
```{r}
m2 <- brm(switch ~ hc * contra_satis + (1 | CASEID),
          family = bernoulli(),
          data = cccu_MA,
          prior = set_priors,
          file = "models/m2.Rds")

summary(m2, prob = .997)
```


## 3.3 Model 3: including not directly with contraceptive method associated predictors
```{r}
m3 <-
  brm(
    switch ~ hc * contra_satis +  hc * sexual_satisfaction + hc * sex_freq + (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA,
    prior = set_priors,
    file = "models/m3.Rds"
  )

summary(m3, prob = .997)

m3_sexual_satisfaction <-
  brm(
    switch ~  hc * sexual_satisfaction  + (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA,
    prior = set_priors,
    file = "models/m3_sexual_satisfaction.Rds"
  )

summary(m3_sexual_satisfaction, prob = .997)

m3_sex_freq <-
  brm(
    switch ~  hc * sex_freq  + (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA,
    prior = set_priors,
    file = "models/m3_sex_freq.Rds"
  )

summary(m3_sex_freq, prob = .997)
```

## 3.4 Model 4: Controlling for observed selection effects
```{r}
m4 <-
  brm(
    switch ~ hc * contra_satis +  hc * sexual_satisfaction + hc * sex_freq +
      hc * AGE + hc * DEGREE_recode +
      hc * POVRATE +
      hc * HLTHPROB_recode + hc * MEDPROB_recode +  hc * GAPINS_recode +
      hc * TYPEINS_recode + hc * NKIDS_t1 +  hc * pregnant_between_waves +
      hc * had_baby_between_waves + hc * Avoid_r +
      hc * FEELPG_recode +
      hc * rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA,
    prior = set_priors,
    file = "models/m4.Rds"
  )

summary(m4, prob = .997)
```






