---
title: "07_MainAnalysis_Robust_Models"
output: html_document
date: "2023-02-03"
---

# 1. Load Packages
```{r}
library(brms)
library(marginaleffects)
library(tidyverse)


options(scipen = 999)

set.seed(180822)

set_priors <- c(prior(normal(0, 1), class = b),
                prior(normal(0, 1), class = sd))
```

# 2. Load Data
```{r}
#MA
load("cccu_R1.RData")

load("cccu_R2.RData")

load("cccu_R3.RData")

```


```{r}
cccu_R1 <- cccu_R1 %>%
  arrange(CASEID) %>%
  mutate_if(is.factor, droplevels)

cccu_R1_hc_only <- cccu_R1 %>%
  filter(hc == "hc") %>%
  mutate_if(is.factor, droplevels)

cccu_R1_nonhc_only <- cccu_R1 %>%
  filter(hc == "non_hc") %>%
  mutate_if(is.factor, droplevels)

cccu_R2 <- cccu_R2 %>%
  arrange(CASEID) %>%
  mutate_if(is.factor, droplevels)

cccu_R2_hc_only <- cccu_R2 %>%
  filter(hc == "hc") %>%
  mutate_if(is.factor, droplevels)

cccu_R2_nonhc_only <- cccu_R2 %>%
  filter(hc == "non_hc") %>%
  mutate_if(is.factor, droplevels)

cccu_R3 <- cccu_R3 %>%
  arrange(CASEID) %>%
  mutate_if(is.factor, droplevels)

cccu_R3_hc_only <- cccu_R3 %>%
  filter(hc == "hc") %>%
  mutate_if(is.factor, droplevels)

cccu_R3_nonhc_only <- cccu_R3 %>%
  filter(hc == "non_hc") %>%
  mutate_if(is.factor, droplevels)

```

# 3. Models of main analyses in robustness analyses

## 3.1 Model 1: basic model

### R1
```{r}
R1_ma_1 <- brm(switch ~ hc + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R1,
          prior = set_priors,
          file = "models/R1_ma_1.Rds")

summary(R1_ma_1, prob = .997)

```

### R2
```{r}
R2_ma_1 <- brm(switch ~ hc + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R2,
          prior = set_priors,
          file = "models/R2_ma_1.Rds")

summary(R2_ma_1, prob = .997)

```


### R3
```{r}
R3_ma_1 <- brm(switch ~ hc + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R3,
          prior = set_priors,
          file = "models/R3_ma_1.Rds")

summary(R3_ma_1, prob = .997)

```


## 3.2 Model 2: including directly with contraceptive method associated predictors

### R1
```{r}
R1_ma_2 <- brm(switch ~ hc * contra_satis + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R1,
          prior = set_priors,
          file = "models/R1_ma_2.Rds")

summary(R1_ma_2, prob = .997)

R1_m2_hc_only  <- brm(switch ~ contra_satis + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R1_hc_only,
          prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
          file = "models/R1_m2_hc_only.Rds")

summary(R1_m2_hc_only, prob = .997)

R1_m2_nonhc_only <- brm(switch ~ contra_satis + (1| CASEID),
                    family = bernoulli(),
                    data = cccu_R1_nonhc_only,
                    prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
                    file = "models/R1_m2_nonhc_only.Rds")

summary(R1_m2_nonhc_only, prob = .997)
```

### R2
```{r}
R2_ma_2 <- brm(switch ~ hc * contra_satis + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R2,
          prior = set_priors,
          file = "models/R2_ma_2.Rds")

summary(R2_ma_2, prob = .997)

R2_m2_hc_only  <- brm(switch ~ contra_satis + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R2_hc_only,
          prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
          file = "models/R2_m2_hc_only.Rds")

summary(R2_m2_hc_only, prob = .997)

R2_m2_nonhc_only <- brm(switch ~ contra_satis + (1| CASEID),
                    family = bernoulli(),
                    data = cccu_R2_nonhc_only,
                    prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
                    file = "models/R2_m2_nonhc_only.Rds")

summary(R2_m2_nonhc_only, prob = .997)
```


### R3
```{r}
R3_ma_2 <- brm(switch ~ hc * contra_satis + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R3,
          prior = set_priors,
          file = "models/R3_ma_2.Rds")

summary(R3_ma_2, prob = .997)

R3_m2_hc_only  <- brm(switch ~ contra_satis + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R3_hc_only,
          prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
          file = "models/R3_m2_hc_only.Rds")

summary(R3_m2_hc_only, prob = .997)

R3_m2_nonhc_only <- brm(switch ~ contra_satis + (1| CASEID),
                    family = bernoulli(),
                    data = cccu_R1_nonhc_only,
                    prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
                    file = "models/R3_m2_nonhc_only.Rds")

summary(R3_m2_nonhc_only, prob = .997)

```


## 3.3 Model 3: including sexual satisfaction & sexual frequency
### R1
```{r}
R1_ma_3 <-
  brm(
    switch ~ hc * contra_satis +  hc * sexual_satisfaction + hc * sex_freq + (1 | CASEID),
    family = bernoulli(),
    data = cccu_R1,
    prior = set_priors,
    file = "models/R1_ma_3.Rds"
  )

summary(R1_ma_3, prob = .997)



R1_ma_3_sexual_satisfaction <-
  brm(
    switch ~  hc * sexual_satisfaction  + (1 | CASEID),
    family = bernoulli(),
    data = cccu_R1,
    prior = set_priors,
    file = "models/R1_ma_3_sexual_satisfaction.Rds"
  )

summary(R1_ma_3_sexual_satisfaction, prob = .997)

R1_ma_3_sex_freq <-
  brm(
    switch ~  hc * sex_freq  + (1 | CASEID),
    family = bernoulli(),
    data = cccu_R1,
    prior = set_priors,
    file = "models/R1_ma_3_sex_freq.Rds"
  )

summary(R1_ma_3_sex_freq, prob = .997)

R1_m3_hc_only  <- brm(switch ~ contra_satis +  sexual_satisfaction + sex_freq + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R1_hc_only,
          prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
          file = "models/R1_m3_hc_only.Rds")

summary(R1_m3_hc_only, prob = .997)

R1_m3_nonhc_only <- brm( switch ~ contra_satis +  sexual_satisfaction + sex_freq +
                           (1| CASEID),
                    family = bernoulli(),
                    data = cccu_R1_nonhc_only,
                    prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
                    file = "models/R1_m3_nonhc_only.Rds")

summary(R1_m3_nonhc_only, prob = .997)

```

### R2
```{r}
R2_ma_3 <-
  brm(
    switch ~ hc * contra_satis +  hc * sexual_satisfaction + hc * sex_freq + (1 | CASEID),
    family = bernoulli(),
    data = cccu_R2,
    prior = set_priors,
    file = "models/R2_ma_3.Rds"
  )

summary(R2_ma_3, prob = .997)



R2_ma_3_sexual_satisfaction <-
  brm(
    switch ~  hc * sexual_satisfaction  + (1 | CASEID),
    family = bernoulli(),
    data = cccu_R2,
    prior = set_priors,
    file = "models/R2_ma_3_sexual_satisfaction.Rds"
  )

summary(R2_ma_3_sexual_satisfaction, prob = .997)

R2_ma_3_sex_freq <-
  brm(
    switch ~  hc * sex_freq  + (1 | CASEID),
    family = bernoulli(),
    data = cccu_R2,
    prior = set_priors,
    file = "models/R2_ma_3_sex_freq.Rds"
  )

summary(R2_ma_3_sex_freq, prob = .997)

R2_m3_hc_only  <- brm( switch ~ contra_satis +  sexual_satisfaction + sex_freq +  (1 | CASEID),
          family = bernoulli(),
          data = cccu_R2_hc_only,
          prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
          file = "models/R2_m3_hc_only.Rds")

summary(R2_m3_hc_only, prob = .997)

R2_m3_nonhc_only <- brm(switch ~ contra_satis +  sexual_satisfaction + sex_freq +  (1| CASEID),
                    family = bernoulli(),
                    data = cccu_R2_nonhc_only,
                    prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
                    file = "models/R2_m3_nonhc_only.Rds")

summary(R2_m3_nonhc_only, prob = .997)
```

### R3
```{r}
R3_ma_3 <-
  brm(
    switch ~ hc * contra_satis +  hc * sexual_satisfaction + hc * sex_freq + (1 | CASEID),
    family = bernoulli(),
    data = cccu_R3,
    prior = set_priors,
    file = "models/R3_ma_3.Rds"
  )

summary(R3_ma_3, prob = .997)



R3_ma_3_sexual_satisfaction <-
  brm(
    switch ~  hc * sexual_satisfaction  + (1 | CASEID),
    family = bernoulli(),
    data = cccu_R3,
    prior = set_priors,
    file = "models/R3_ma_3_sexual_satisfaction.Rds"
  )

summary(R3_ma_3_sexual_satisfaction, prob = .997)

R3_ma_3_sex_freq <-
  brm(
    switch ~  hc * sex_freq  + (1 | CASEID),
    family = bernoulli(),
    data = cccu_R3,
    prior = set_priors,
    file = "models/R3_ma_3_sex_freq.Rds"
  )

summary(R3_ma_3_sex_freq, prob = .997)

R3_m3_hc_only  <- brm( switch ~ contra_satis +  sexual_satisfaction + sex_freq + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R3_hc_only,
          prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
          file = "models/R3_m3_hc_only.Rds")

summary(R3_m3_hc_only, prob = .997)

R3_m3_nonhc_only <- brm(switch ~ contra_satis +  sexual_satisfaction + sex_freq +  (1| CASEID),
                    family = bernoulli(),
                    data = cccu_R3_nonhc_only,
                    prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
                    file = "models/R3_m3_nonhc_only.Rds")

summary(R3_m3_nonhc_only, prob = .997)
```




## 3.4 Model 4: Controlling for observed selection effects

### R1
```{r}
R1_ma_4 <-
  brm(
    switch ~ hc * contra_satis +  hc * sexual_satisfaction + hc * sex_freq +
      hc * AGE + hc * DEGREE_recode +
      hc * POVRATE +
      hc * HLTHPROB_recode + hc * MEDPROB_recode +  hc * GAPINS_recode +
      hc * TYPEINS_recode + hc * NKIDS_t1 +  hc * pregnant_between_waves +
      hc * had_baby_between_waves + hc * Avoid_r +
      hc * FEELPG_recode +
      hc * rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_R1,
    prior = set_priors,
    file = "models/R1_ma_4.Rds"
  )

summary(R1_ma_4, prob = .997)

R1_m4_hc_only <-
  brm(
    switch ~ contra_satis +  sexual_satisfaction + sex_freq +
      AGE + DEGREE_recode +
      POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r +
      FEELPG_recode +
      rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_R1_hc_only,
    prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
    file = "models/R1_m4_hc_only.Rds"
  )

summary(R1_m4_hc_only, prob = .997)

R1_m4_nonhc_only <-
  brm(
    switch ~ contra_satis +  sexual_satisfaction + sex_freq +
      AGE + DEGREE_recode +
      POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r +
      FEELPG_recode +
      rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_R1_nonhc_only,
    prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
    file = "models/R1_m4_nonhc_only.Rds"
  )

summary(R1_m4_nonhc_only, prob = .997)
```

### R2
```{r}
R2_ma_4 <-
  brm(
    switch ~ hc * contra_satis +  hc * sexual_satisfaction + hc * sex_freq +
      hc * AGE + hc * DEGREE_recode +
      hc * POVRATE +
      hc * HLTHPROB_recode + hc * MEDPROB_recode +  hc * GAPINS_recode +
      hc * TYPEINS_recode + hc * NKIDS_t1 +  hc * pregnant_between_waves +
      hc * had_baby_between_waves + hc * Avoid_r +
      hc * FEELPG_recode +
      hc * rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_R2,
    prior = set_priors,
    file = "models/R2_ma_4.Rds"
  )

summary(R2_ma_4, prob = .997)


R2_m4_hc_only <-
  brm(
    switch ~ contra_satis +  sexual_satisfaction + sex_freq +
      AGE + DEGREE_recode +
      POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r +
      FEELPG_recode +
      rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_R2_hc_only,
    prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
    file = "models/R2_m4_hc_only.Rds"
  )

summary(R2_m4_hc_only, prob = .997)

R2_m4_nonhc_only <-
  brm(
    switch ~ contra_satis +  sexual_satisfaction + sex_freq +
      AGE + DEGREE_recode +
      POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r +
      FEELPG_recode +
      rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_R1_nonhc_only,
    prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
    file = "models/R2_m4_nonhc_only.Rds"
  )

summary(R2_m4_nonhc_only, prob = .997)
```


### R3
```{r}
R3_ma_4 <-
  brm(
    switch ~ hc * contra_satis +  hc * sexual_satisfaction + hc * sex_freq +
      hc * AGE + hc * DEGREE_recode +
      hc * POVRATE +
      hc * HLTHPROB_recode + hc * MEDPROB_recode +  hc * GAPINS_recode +
      hc * TYPEINS_recode + hc * NKIDS_t1 +  hc * pregnant_between_waves +
      hc * had_baby_between_waves + hc * Avoid_r +
      hc * FEELPG_recode +
      hc * rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_R3,
    prior = set_priors,
    file = "models/R3_ma_4.Rds"
  )

summary(R3_ma_4, prob = .997)


R3_m4_hc_only <-
  brm(
    switch ~ contra_satis +  sexual_satisfaction + sex_freq +
      AGE + DEGREE_recode +
      POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r +
      FEELPG_recode +
      rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_R3_hc_only,
    prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
    file = "models/R3_m4_hc_only.Rds"
  )

summary(R3_m4_hc_only, prob = .997)

R3_m4_nonhc_only <-
  brm(
    switch ~ contra_satis +  sexual_satisfaction + sex_freq +
      AGE + DEGREE_recode +
      POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r +
      FEELPG_recode +
      rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_R3_nonhc_only,
    prior = set_priors,
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99),
    file = "models/R3_m4_nonhc_only.Rds"
  )

summary(R3_m4_nonhc_only, prob = .997)
```


