---
title: "07_Subanalysis"
author: "Chiara Draxler"
date: "24 1 2022"
output: html_document
---
#1. Load Data
```{r}

load("cccu_SA.RData")
length(unique(cccu_SA$CASEID)) #women
```


#2. Load Packages
```{r}
library(lme4)
library(marginaleffects)
library(formr)
library(effects)
library(EValue)
library(psych)
library(dplyr)
library(tidyverse)
library(marginaleffects)

options(scipen=999)
```


#3. Models


##3.2 Model 2: including directly with contraceptive method associated predictors

DURATION and satisfaction!

```{r}
sa_m2 <- glmer(switch ~ contra_satis * hc_dur + (1| CASEID), family = binomial, data = cccu_SA, control=glmerControl(optimizer="bobyqa"))

summary(sa_m2)
confint(sa_m2, method = "Wald", level = .997)
plot(allEffects(sa_m2))
```


##3.3 Model 3: including not directly with contraceptive method associated predictors
```{r}
sa_m3 <- glmer(switch ~ contra_satis* hc_dur  +  sexual_satisfaction +  sex_freq + (1| CASEID), family = binomial, data = cccu_SA, control=glmerControl(optimizer="bobyqa"))

summary(sa_m3)
confint(sa_m3, method = "Wald", level = .997)
plot(allEffects(sa_m3))
```

##3.4 Model 4: Controlling for observed selection effects
```{r}
#filter for first measurement occasion
length(unique(cccu_SA$CASEID))


cccu_SA_sens = cccu_SA %>%
  group_by(CASEID) %>%
  arrange(WAVE) %>%
  mutate(count = row_number()) %>%
  ungroup()

cccu_SA_sens = cccu_SA_sens %>%
  filter(count == 1)

table(cccu_SA_sens$WAVE)


#repeating model 3 as linear model 
sa_m3_lm <- glm(switch ~ contra_satis* hc_dur  +  sexual_satisfaction +  sex_freq, family = binomial, data = cccu_SA_sens)

summary(sa_m3_lm)
confint(sa_m3_lm, method = "Wald", level = .997)
plot(allEffects(sa_m3_lm))

#model 4 as linear model (did not converge otherwise)

sa_m4_lm <- glm(switch ~ contra_satis*hc_dur +  sexual_satisfaction +   sex_freq + AGE + DEGREE_recode + POVRATE + HLTHPROB_recode + MEDPROB_recode + GAPINS_recode +
              TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves + had_baby_between_waves+ Avoid_r + FEELPG_recode +
              rel_dur_factor,
            family = binomial,
            data = cccu_SA_sens)

summary(sa_m4_lm)
confint(sa_m4_lm, method = "Wald", level = .997)
plot(allEffects(sa_m4_lm))
```


###Average marginal effects
####m2
```{r}
#average marginal effect
ame <- marginaleffects(sa_m2)
summary(ame)
```

####m3
```{r}
#average marginal effect
ame <- marginaleffects(sa_m3)
summary(ame)
```

####m4
```{r}
#average marginal effect

ame <- marginaleffects(sa_m3_lm)
summary(ame)
ame <- marginaleffects(sa_m4_lm)
summary(ame)

```


