---
title: "08_MainAnalysis_AME"
output: html_document
date: "2023-02-03"
---

# 1. Load Packages
```{r}
library(brms)
library(marginaleffects)
library(tidyverse)



options(scipen = 999)

set.seed(180822)

set_priors <- c(prior(normal(0, 1), class = b),
                prior(normal(0, 1), class = sd))
```

# 2. Load Data
```{r}
load("cccu_MA.RData")

cccu_MA <- cccu_MA %>%
  arrange(CASEID) %>%
  mutate(hc = droplevels(hc))
```

# 3. Load models of main analysis
```{r}
m1 <- brm(file = "models/m1.Rds")
m2 <- brm(file = "models/m2.Rds")
m3 <- brm(file = "models/m3.Rds")
m4 <- brm(file = "models/m4.Rds")
```

# 4. Compute Average marginal effects

## m1
```{r}
#average marginal effect
ame <- marginaleffects(m1)
summary(ame, conf_level = .997)
```

## m2
```{r}
#average marginal effect
ame <- marginaleffects(m2)
summary(ame, conf_level = .997)

m2_hc_only <- brm(
  switch ~ contra_satis + (1 | CASEID),
  family = bernoulli(),
  data = cccu_MA %>% filter(hc == "hc"),
  prior = set_priors,
  file = "models/m2_hc_only.Rds"
)
ame <- marginaleffects(m2_hc_only)
summary(ame, conf_level = .997)

m2_nonhc_only <- brm(
  switch ~ contra_satis + (1 | CASEID),
  family = bernoulli(),
  data = cccu_MA %>% filter(hc == "non_hc"),
  prior = set_priors,
  file = "models/m2_nonhc_only.Rds"
)
ame <- marginaleffects(m2_nonhc_only)
summary(ame, conf_level = .997)
```

## m3
```{r}
#average marginal effect
ame <- marginaleffects(m3)
summary(ame, conf_level = .997)

m3_hc_only <-
  brm(
    switch ~ contra_satis + sexual_satisfaction + sex_freq +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA %>% filter(hc == "hc"),
  prior = set_priors,
  file = "models/m3_hc_only.Rds"
  )
ame <- marginaleffects(m3_hc_only)
summary(ame, conf_level = .997)


m3_nonhc_only <-
  brm(
    switch ~ contra_satis + sexual_satisfaction + sex_freq +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA %>% filter(hc == "non_hc"),
  prior = set_priors,
  file = "models/m3_nonhc_only.Rds"
  )
ame <- marginaleffects(m3_nonhc_only)
summary(ame, conf_level = .997)
```

## m4
```{r}
#model 4
ame <- marginaleffects(m4)
summary(ame, conf_level = .997)

m4_hc_only <-
  brm(
    switch ~ contra_satis + sexual_satisfaction +  sex_freq +
      AGE + DEGREE_recode + POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r + FEELPG_recode +
      rel_dur_factor + (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA %>% filter(hc == "hc"),
  prior = set_priors,
  file = "models/m4_hc_only.Rds"
  )

ame <- marginaleffects(m4_hc_only)
summary(ame, conf_level = .997)

m4_nonhc_only <-
  brm(
    switch ~ contra_satis + sexual_satisfaction +  sex_freq +
      AGE + DEGREE_recode + POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r + FEELPG_recode +
      rel_dur_factor + (1 | CASEID),
    family = bernoulli(),
    data = cccu_MA %>% filter(hc == "non_hc"),
  prior = set_priors,
  file = "models/m4_nonhc_only.Rds"
  )

ame <- marginaleffects(m4_nonhc_only)
summary(ame, conf_level = .997)
```