---
title: "09_MainAnalyis_Robust_Models_AME"
output: html_document
date: "2023-02-03"
---

# 1. Load Packages
```{r}
library(brms)
library(marginaleffects)
library(tidyverse)


options(scipen = 999)

set.seed(180822)

set_priors <- c(prior(normal(0, 1), class = b),
                prior(normal(0, 1), class = sd))
```

# 2. Load Data
```{r}
#MA
load("cccu_R1.RData")

load("cccu_R2.RData")

load("cccu_R3.RData")

```


```{r}
cccu_R1 <- cccu_R1 %>%
  arrange(CASEID)

cccu_R2 <- cccu_R2 %>%
  arrange(CASEID)

cccu_R3 <- cccu_R3 %>%
  arrange(CASEID)

```

#3. Load models of main analysis
```{r}
R1_ma_1 <- brm(file = "models/R1_ma_1.Rds")
R2_ma_1<- brm(file = "models/R2_ma_1.Rds")
R3_ma_1 <- brm(file = "models/R3_ma_1.Rds")

R1_ma_2 <- brm(file = "models/R1_ma_2.Rds")
R2_ma_2<- brm(file = "models/R2_ma_2.Rds")
R3_ma_2 <- brm(file = "models/R3_ma_2.Rds")

R1_ma_3 <- brm(file = "models/R1_ma_3.Rds")
R2_ma_3<- brm(file = "models/R2_ma_3.Rds")
R3_ma_3 <- brm(file = "models/R3_ma_3.Rds")
               
R1_ma_4 <- brm(file = "models/R1_ma_4.Rds")
R2_ma_4<- brm(file = "models/R2_ma_4.Rds")
R3_ma_4 <- brm(file = "models/R3_ma_4.Rds")
```
# 4. Average marginal effects for models in main analyses for robustness analyses

## Model1
### R1
```{r}

#average marginal effect
ame <- marginaleffects(R1_ma_1)
summary(ame, conf_level = .997)


```

### R2
```{r}
#average marginal effect
ame <- marginaleffects(R2_ma_1)
summary(ame, conf_level = .997)


```

### R3
```{r}
#average marginal effect
ame <- marginaleffects(R3_ma_1)
summary(ame, conf_level = .997)


```

## Model 2
### R1
```{r}
#average marginal effect
ame <- marginaleffects(R1_ma_2)
summary(ame, conf_level = .997)


R1_m2_hc_only  <- brm(switch ~ contra_satis + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R1%>% filter(hc == "hc"),
          prior = set_priors,
          file = "models/R1_m2_hc_only.Rds")

ame <- marginaleffects(R1_m2_hc_only)
summary(ame, conf_level = .997)

R1_m2_nonhc_only <- brm(switch ~ contra_satis + (1| CASEID),
                    family = bernoulli(),
                    data = cccu_R1 %>% filter(hc == "non_hc"),
                    prior = set_priors,
                    file = "models/R1_m2_nonhc_only.Rds")

ame <- marginaleffects(R1_m2_nonhc_only)
summary(ame, conf_level = .997)
```

### R2
```{r}
#average marginal effect
ame <- marginaleffects(R2_ma_2)
summary(ame, conf_level = .997)

R2_m2_hc_only  <- brm(switch ~ contra_satis + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R2%>% filter(hc == "hc"),
          prior = set_priors,
          file = "models/R2_m2_hc_only.Rds")
ame <- marginaleffects(R2_m2_hc_only)
summary(ame, conf_level = .997)

R2_m2_nonhc_only <- brm(switch ~ contra_satis + (1| CASEID),
                    family = bernoulli(),
                    data = cccu_R2 %>% filter(hc == "non_hc"),
                    prior = set_priors,
                    file = "models/R2_m2_nonhc_only.Rds")
ame <- marginaleffects(R2_m2_nonhc_only)
summary(ame, conf_level = .997)
```

### R3
```{r}
#average marginal effect
ame <- marginaleffects(R3_ma_2)
summary(ame, conf_level = .997)


R3_m2_hc_only  <- brm(switch ~ contra_satis + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R3%>% filter(hc == "hc"),
          prior = set_priors,
          file = "models/R3_m2_hc_only.Rds")
ame <- marginaleffects(R3_m2_hc_only)
summary(ame, conf_level = .997)

R3_m2_nonhc_only <- brm(switch ~ contra_satis + (1| CASEID),
                    family = bernoulli(),
                    data = cccu_R3 %>% filter(hc == "non_hc"),
                    prior = set_priors,
                    file = "models/R3_m2_nonhc_only.Rds")
ame <- marginaleffects(R3_m2_nonhc_only)
summary(ame, conf_level = .997)
```

## Model 3

### R1

```{r}
#average marginal effect
ame <- marginaleffects(R1_ma_3)
summary(ame, conf_level = .997)


R1_m3_hc_only  <- brm(switch ~ contra_satis +  sexual_satisfaction + sex_freq + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R1%>% filter(hc == "hc"),
          prior = set_priors,
          file = "models/R1_m3_hc_only.Rds")
ame <- marginaleffects(R1_m3_hc_only)
summary(ame, conf_level = .997)

R1_m3_nonhc_only <- brm( switch ~ contra_satis +  sexual_satisfaction + sex_freq +
                           (1| CASEID),
                    family = bernoulli(),
                    data = cccu_R1 %>% filter(hc == "non_hc"),
                    prior = set_priors,
                    file = "models/R1_m3_nonhc_only.Rds")
ame <- marginaleffects(R1_m3_nonhc_only)
summary(ame, conf_level = .997)
```



### R2
```{r}
#average marginal effect
ame <- marginaleffects(R2_ma_3)
summary(ame, conf_level = .997)


R2_m3_hc_only  <- brm( switch ~ contra_satis +  sexual_satisfaction + sex_freq +  (1 | CASEID),
          family = bernoulli(),
          data = cccu_R2%>% filter(hc == "hc"),
          prior = set_priors,
          file = "models/R2_m3_hc_only.Rds")
ame <- marginaleffects(R2_m3_hc_only)
summary(ame, conf_level = .997)

R2_m3_nonhc_only <- brm(switch ~ contra_satis +  sexual_satisfaction + sex_freq +  (1| CASEID),
                    family = bernoulli(),
                    data = cccu_R2 %>% filter(hc == "non_hc"),
                    prior = set_priors,
                    file = "models/R2_m3_nonhc_only.Rds")
ame <- marginaleffects(R2_m3_nonhc_only)
summary(ame, conf_level = .997)
```

### R3
```{r}
#average marginal effect
ame <- marginaleffects(R3_ma_3)
summary(ame, conf_level = .997)

R3_m3_hc_only  <- brm( switch ~ contra_satis +  sexual_satisfaction + sex_freq + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R3%>% filter(hc == "hc"),
          prior = set_priors,
          file = "models/R3_m3_hc_only.Rds")
ame <- marginaleffects(R3_m3_hc_only)
summary(ame, conf_level = .997)

R3_m3_nonhc_only <- brm(switch ~ contra_satis +  sexual_satisfaction + sex_freq +  (1| CASEID),
                    family = bernoulli(),
                    data = cccu_R3 %>% filter(hc == "non_hc"),
                    prior = set_priors,
                    file = "models/R3_m3_nonhc_only.Rds")
ame <- marginaleffects(R3_m3_nonhc_only)
summary(ame, conf_level = .997)
```

## Model 4
### R1
```{r}

ame <- marginaleffects(R1_ma_4)
summary(ame, conf_level = .997)

R1_m4_hc_only <-
  brm(
    switch ~ contra_satis +  sexual_satisfaction + sex_freq +
      AGE + DEGREE_recode +
      POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r +
      FEELPG_recode +
      rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_R1 %>% filter(hc == "hc"),
    prior = set_priors,
    file = "models/R1_m4_hc_only.Rds"
  )


ame <- marginaleffects(R1_m4_hc_only)
summary(ame, conf_level = .997)


R1_m4_nonhc_only <-
  brm(
    switch ~ contra_satis +  sexual_satisfaction + sex_freq +
      AGE + DEGREE_recode +
      POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r +
      FEELPG_recode +
      rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_R1%>% filter(hc == "non_hc"),
    prior = set_priors,
    file = "models/R1_m4_nonhc_only.Rds"
  )


ame <- marginaleffects(R1_m4_nonhc_only)
summary(ame, conf_level = .997)


```

### R2
```{r}
#average marginal effect
ame <- marginaleffects(R2_ma_4)
summary(ame, conf_level = .997)

R2_m4_hc_only <-
  brm(
    switch ~ contra_satis +  sexual_satisfaction + sex_freq +
      AGE + DEGREE_recode +
      POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r +
      FEELPG_recode +
      rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_R2%>% filter(hc == "hc"),
    prior = set_priors,
    file = "models/R2_m4_hc_only.Rds"
  )


ame <- marginaleffects(R2_m4_hc_only)
summary(ame, conf_level = .997)


R2_m4_nonhc_only <-
  brm(
    switch ~ contra_satis +  sexual_satisfaction + sex_freq +
      AGE + DEGREE_recode +
      POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r +
      FEELPG_recode +
      rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_R2%>% filter(hc == "non_hc"),
    prior = set_priors,
    file = "models/R2_m4_nonhc_only.Rds"
  )


ame <- marginaleffects(R2_m4_nonhc_only)
summary(ame, conf_level = .997)


```

### R3
```{r}

ame <- marginaleffects(R3_ma_4)
summary(ame, conf_level = .997)

R3_m4_hc_only <-
  brm(
    switch ~ contra_satis +  sexual_satisfaction + sex_freq +
      AGE + DEGREE_recode +
      POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r +
      FEELPG_recode +
      rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_R3%>% filter(hc == "hc"),
    prior = set_priors,
    file = "models/R3_m4_hc_only.Rds"
  )


ame <- marginaleffects(R3_m4_hc_only)
summary(ame, conf_level = .997)


R3_m4_nonhc_only <-
  brm(
    switch ~ contra_satis +  sexual_satisfaction + sex_freq +
      AGE + DEGREE_recode +
      POVRATE +
      HLTHPROB_recode + MEDPROB_recode +  GAPINS_recode +
      TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves +
      had_baby_between_waves + Avoid_r +
      FEELPG_recode +
      rel_dur_factor +
      (1 | CASEID),
    family = bernoulli(),
    data = cccu_R3%>% filter(hc == "non_hc"),
    prior = set_priors,
    file = "models/R3_m4_nonhc_only.Rds"
  )


ame <- marginaleffects(R3_m4_nonhc_only)
summary(ame, conf_level = .997)

```


