---
title: "09_plots"
output: html_document
date: '2022-06-28'
---

##1. Load Data
```{r}
load("cccu_MA.RData")
load("cccu_SA.RData")
```


##2. Load Packages
```{r}
library(formr)
library(effects)
library(EValue)
library(lme4)
library(psych)
library(dplyr)
library(tidyverse)
library(patchwork)
library(marginaleffects)
library(ggpubr)
library(RColorBrewer)



options(scipen=999)

apatheme=theme_bw()+
    theme(panel.grid.major=element_blank(),
          panel.grid.minor=element_blank(),
          panel.border=element_blank(),
          axis.line=element_line(),
          text=element_text(family='Times'))
```


## 3. Specific effects
Plots for
- hc*contra_satis
- hc*sexual_satisfaction
- hc*sex_freq
- hc_dur*contra_satis
based on multilevel model m3
```{r}
m3 <- glmer(switch ~ hc * contra_satis +  hc * sexual_satisfaction + hc * sex_freq + (1| CASEID), family = binomial, data = cccu_MA, control=glmerControl(optimizer="bobyqa"))

plot(effect(term = "hc * contra_satis", mod = m3, confidence.level = 0.997))

eff = allEffects(mod = m3, confidence.level = 0.997)

#contraceptive satisfaction

eff_contra_satis = eff$`hc:contra_satis`

eff_contra_satis_datplot = data.frame(
  hc = eff_contra_satis$x$hc,
  contra_satis = eff_contra_satis$x$contra_satis,
  estimate = eff_contra_satis$fit,
  lower = eff_contra_satis$lower,
  upper = eff_contra_satis$upper)


plot_contra_satis <- ggplot(data = eff_contra_satis_datplot,
                            aes(
                              x = contra_satis,
                              y = estimate,
                              group = hc,
                              color = hc,
                              fill = hc
                            )) +
  geom_line() +
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = hc),
              alpha = 0.07) +
  labs(color = "Group",  fill = "Group") +
  scale_fill_manual(
    values = c("red", "blue"),
    name = "Group",
    breaks = c("hc", "non_hc"),
    labels = c(
      "Hormonal Contraceptive Users",
      "Non-Hormonal Contraceptive Users"
    ),
  ) +
  scale_colour_manual(
    values = c("red", "blue"),
    name  = "Group",
    breaks = c("hc", "non_hc"),
    labels = c(
      "Hormonal Contraceptive Users",
      "Non-Hormonal Contraceptive Users"
    )
  ) +
  labs(y = "Probability to Switch") +
  scale_x_discrete("Contraceptive Satisfaction",
                   limits = c("1", "2", "3", "4")) +
  
  apatheme

plot_contra_satis

#sexual satisfaction

eff_sexual_satisfaction = eff$`hc:sexual_satisfaction`

eff_sexual_satisfaction_datplot = data.frame(
  hc = eff_sexual_satisfaction$x$hc,
  sex_sat = eff_sexual_satisfaction$x$sexual_satisfaction,
  estimate = eff_sexual_satisfaction$fit,
  lower = eff_sexual_satisfaction$lower,
  upper = eff_sexual_satisfaction$upper)



plot_sexual_satisfaction <-
  ggplot(data = eff_sexual_satisfaction_datplot,
         aes(
           x = sex_sat,
           y = estimate,
           group = hc,
           color = hc,
           fill = hc
         )) +
  geom_line() +
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = hc),
              alpha = 0.07) +
  labs(color = "Group",  fill = "Group") +
  scale_fill_manual(
    values = c("red", "blue"),
    name = "Group",
    breaks = c("hc", "non_hc"),
    labels = c(
      "Hormonal Contraceptive Users",
      "Non-Hormonal Contraceptive Users"
    )
  ) +
  scale_colour_manual(
    values = c("red", "blue"),
    name  = "Group",
    breaks = c("hc", "non_hc"),
    labels = c(
      "Hormonal Contraceptive Users",
      "Non-Hormonal Contraceptive Users"
    )
  ) +
  labs(y = "Probability to Switch") +
  scale_x_discrete("Sexual Satisfaction",
                   limits = c("1", "2", "3", "4", "5", "6")) +
  
  apatheme


    
plot_sexual_satisfaction

#sexual frequency 

eff_sex_freq = eff$`hc:sex_freq`

eff_sex_freq_datplot = data.frame(
  hc = eff_sex_freq$x$hc,
  sex_freq = eff_sex_freq$x$sex_freq,
  estimate = eff_sex_freq$fit,
  lower = eff_sex_freq$lower,
  upper = eff_sex_freq$upper)


plot_sex_freq <- ggplot(data = eff_sex_freq_datplot,
                        aes(
                          x = sex_freq,
                          y = estimate,
                          group = hc,
                          color = hc,
                          fill = hc
                        )) +
  geom_line() +
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = hc),
              alpha = 0.07) +
  labs(color = "Group",  fill = "Group") +
  scale_fill_manual(
    values = c("red", "blue"),
    name = "Group",
    breaks = c("hc", "non_hc"),
    labels = c(
      "Hormonal Contraceptive Users",
      "Non-Hormonal Contraceptive Users"
    )
  ) +
  scale_colour_manual(
    values = c("red", "blue"),
    name  = "Group",
    breaks = c("hc", "non_hc"),
    labels = c(
      "Hormonal Contraceptive Users",
      "Non-Hormonal Contraceptive Users"
    )
  ) +
  labs(y = "Probability to Switch") +
  scale_x_discrete(
    "Sexual Frequency",
    limits = c("11 or more times", "6-10 times", "2-5 times", "No sex or once")
  ) +
  apatheme

plot_sex_freq

#for hc dur

sa_m3 <- glmer(switch ~ contra_satis* hc_dur  +  sexual_satisfaction +  sex_freq + (1| CASEID), family = binomial, data = cccu_SA, control=glmerControl(optimizer="bobyqa"))
summary(sa_m3)

plot(effect(term = "contra_satis* hc_dur", mod = sa_m3, confidence.level = 0.997))

eff = allEffects(mod = sa_m3, confidence.level = 0.997)

#contraceptive satisfaction

eff_hc_dur = eff$`contra_satis:hc_dur`

eff_hc_dur_datplot = data.frame(
  hc_dur = eff_hc_dur$x$hc_dur,
  contra_satis = eff_hc_dur$x$contra_satis,
  estimate = eff_hc_dur$fit,
  lower = eff_hc_dur$lower,
  upper = eff_hc_dur$upper)

nickColors <- function(n, h = c(120,400), l = c(.40,.70), s = c(.8,1), alpha = 3){
  require(colorspace)
  require(scales)
  return (alpha(hex(HLS(seq(h[1],h[2],length.out = n), seq(l[1],l[2],length.out = n), seq(s[1],s[2],length.out=n))), alpha))
}
barplot(rep(1,12), col = nickColors(12))


plot_hc_dur <- ggplot(data = eff_hc_dur_datplot,
                      aes(
                        x = contra_satis,
                        y = estimate,
                        group = hc_dur,
                        color = hc_dur,
                        fill = hc_dur
                      )) +
  geom_line() +
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = hc_dur),
              alpha = 0.03) +
  labs(y = "Probability to Switch", color = "Contraceptive Duration", fill = "Contraceptive Duration") +
  scale_x_discrete("Contraceptive Satisfaction",
                   limits = c("1", "2", "3", "4")) +
  scale_fill_gradientn(
    colors = nickColors(12),
    breaks = c(0, 10, 20, 30, 40),
    labels = c("0 Months", "10 Months", "20 Months", "30 Months", "40 Months")
  ) +
  scale_color_gradientn(
    colors = nickColors(12),
    breaks = c(0, 10, 20, 30, 40),
    labels = c("0 Months", "10 Months", "20 Months", "30 Months", "40 Months")
  ) +
  apatheme

plot_hc_dur



plot_hc_dur_separate <- ggplot(data = eff_hc_dur_datplot,
                      aes(
                        x = contra_satis,
                        y = estimate,
                        group = hc_dur,
                        color = hc_dur,
                        fill = hc_dur
                      )) +
  geom_line() +
  geom_ribbon(aes(ymin = lower, ymax = upper, fill = hc_dur),
              alpha = 0.07)+
    facet_wrap(~hc_dur, nrow = 1)+
  labs(y = "Probability to Switch", color = "Contraceptive Duration", fill = "Contraceptive Duration") +
  scale_x_discrete("Contraceptive Satisfaction",
                   limits = c("1", "2", "3", "4")) +
  scale_fill_continuous(
    breaks = c(0, 10, 20, 30, 40),
    labels = c("0 Months", "10 Months", "20 Months", "30 Months", "40 Months")
  ) +
  scale_color_continuous(
    breaks = c(0, 10, 20, 30, 40),
    labels = c("0 Months", "10 Months", "20 Months", "30 Months", "40 Months")
  ) +
  apatheme


plot_hc_dur_separate



#join plots
figure <-
  ggarrange(
    plot_contra_satis,
    plot_sexual_satisfaction,
    plot_sex_freq,
    common.legend = TRUE,legend = "right",
    labels = c("A", "B", "C"),
    ncol = 2,
    nrow = 2
  )
figure


```



## 4. Forest plot main effects
for models m3, m3_lm, and m4_lm

### Models
```{r}
m3 <- glmer(switch ~ hc * contra_satis +  hc * sexual_satisfaction + hc * sex_freq + (1| CASEID), family = binomial, data = cccu_MA, control=glmerControl(optimizer="bobyqa"))
m3_sum = summary(m3)
```

```{r}
#filter for first measurement occasion
length(unique(cccu_MA$CASEID))


cccu_MA_sens = cccu_MA %>%
  group_by(CASEID) %>%
  arrange(WAVE) %>%
  mutate(count = row_number()) %>%
  ungroup()

cccu_MA_sens = cccu_MA_sens %>%
  filter(count == 1)

table(cccu_MA_sens$WAVE)

#repeat model 3 for sensitivity analyses
m3_lm = glm(switch ~ hc * contra_satis + hc * sexual_satisfaction +  hc * sex_freq,
          family = binomial,
          data = cccu_MA_sens)
```

```{r}
m4_lm = glm(switch ~ hc * contra_satis + hc * sexual_satisfaction +  hc * sex_freq + hc *AGE + hc *DEGREE_recode +
              hc *POVRATE +
              hc *HLTHPROB_recode + hc *MEDPROB_recode +  hc *GAPINS_recode +
              hc *TYPEINS_recode + hc *NKIDS_t1 +  hc *pregnant_between_waves + hc *had_baby_between_waves+ hc *Avoid_r +
              hc *FEELPG_recode +
              hc *rel_dur_factor,
            family = binomial,
            data = cccu_MA_sens)
summary(m4_lm)
```

### Effects and CIs
```{r}
m3_confint = confint(m3, method = "Wald", level = .997) 

rn = rownames(m3_confint)
m3_confint = data.frame(m3_confint)

colnames(m3_confint) = c("lower", "upper")
m3_confint$predictor = rn


m3_forest_plot = data.frame(
  predictor = names(m3_sum$coefficients[,1]),
  estimate = as.numeric(as.character(m3_sum$coefficients[,1])))

m3_forest_plot = left_join(m3_forest_plot, m3_confint, by = "predictor")

m3_forest_plot$group = rep("multilevel_model_3", 12)

```

```{r}
m3_lm_confint = confint(m3_lm, method = "Wald", level = .997) 

rn = rownames(m3_lm_confint)
m3_lm_confint = data.frame(m3_lm_confint)

colnames(m3_lm_confint) = c("lower", "upper")
m3_lm_confint$predictor = rn


m3_lm_forest_plot = data.frame(
  predictor = names(m3_lm$coefficients),
  estimate = as.numeric(as.character(m3_lm$coefficients)))

m3_lm_forest_plot = left_join(m3_lm_forest_plot, m3_lm_confint, by = "predictor")

m3_lm_forest_plot$group = rep("model_3", 12)
```

```{r}
m4_lm_confint = confint(m4_lm, parm = c("(Intercept)",
                                               "hcnon_hc",
                                               "contra_satis",
                                               "sexual_satisfaction",
                                               "sex_freq2-5 times", "sex_freq6-10 times",
                                               "sex_freq11 or more times", 
                                               "hcnon_hc:contra_satis",
                                               "hcnon_hc:sexual_satisfaction",
                                               "hcnon_hc:sex_freq2-5 times",
                                               "hcnon_hc:sex_freq6-10 times",
                                               "hcnon_hc:sex_freq11 or more times"),
                        method = "Wald", level = .997) 

rn = rownames(m4_lm_confint)
m4_lm_confint = data.frame(m4_lm_confint)

colnames(m4_lm_confint) = c("lower", "upper")
m4_lm_confint$predictor = rn


m4_lm_forest_plot = data.frame(
  predictor = names(m4_lm$coefficients),
  estimate = as.numeric(as.character(m4_lm$coefficients)))

m4_lm_forest_plot = left_join(m4_lm_forest_plot, m4_lm_confint, by = "predictor")

m4_lm_forest_plot$group = rep("model_4", 12)
```

### Dataframe for plot
```{r}
forest_plot_data = rbind(m3_forest_plot, m3_lm_forest_plot, m4_lm_forest_plot)
forest_plot_data$predictor = factor(forest_plot_data$predictor,
                                    levels = c("(Intercept)",
                                               "hcnon_hc",
                                               "contra_satis",
                                               "sexual_satisfaction",
                                               "sex_freq2-5 times", "sex_freq6-10 times",
                                               "sex_freq11 or more times", 
                                               "hcnon_hc:contra_satis",
                                               "hcnon_hc:sexual_satisfaction",
                                               "hcnon_hc:sex_freq2-5 times",
                                               "hcnon_hc:sex_freq6-10 times",
                                               "hcnon_hc:sex_freq11 or more times"),
                                    labels = c("(Intercept)",
                                               "hcnon_hc",
                                               "contra_satis",
                                               "sexual_satisfaction",
                                               "sex_freq2-5 times", "sex_freq6-10 times",
                                               "sex_freq11 or more times", 
                                               "hcnon_hc:contra_satis",
                                               "hcnon_hc:sexual_satisfaction",
                                               "hcnon_hc:sex_freq2-5 times",
                                               "hcnon_hc:sex_freq6-10 times",
                                               "hcnon_hc:sex_freq11 or more times"))

forest_plot_data$group = factor(forest_plot_data$group,
                                levels = c("multilevel_model_3", "model_3", "model_4"),
                                labels = c("multilevel_model_3", "model_3", "model_4"))

```

### Plot
```{r}
ggplot(data = forest_plot_data %>%
         filter(predictor != "(Intercept)"),
       aes(x = predictor,
           y = estimate,
           group = group,
           fill = group,
           color = group)) +
  geom_point(position = position_dodge(width=-0.3)) +
  geom_pointrange(aes(ymin = lower, ymax = upper), position = position_dodge(width=-0.3)) +
  scale_x_discrete(limits=rev) +
  geom_hline(yintercept = 0) +
  coord_flip() +
  apatheme

```


