---
title: "11_SubAnalysis_Models"
author: "Chiara Draxler"
date: "16 11 2022"
output: html_document
---
# 1. Load Packages
```{r}
library(brms)
library(marginaleffects)
library(tidyverse)


options(scipen = 999)

set.seed(180822)

set_priors <- c(prior(normal(0, 1), class = b),
                prior(normal(0, 1), class = sd))
```

# 2. Load Data
```{r}
load("cccu_SA.RData")

cccu_SA <- cccu_SA %>%
  arrange(CASEID) %>%
  mutate_if(is.factor, droplevels)
```

# 3. Models


## 3.2 Model 2: including directly with contraceptive method associated predictors

DURATION and satisfaction!

```{r}
sa_m2 <- brm(switch ~ contra_satis * hc_dur + (1 | CASEID),
          family = bernoulli(),
          data = cccu_SA,
          prior = set_priors,
          file = "models/sa_m2.Rds",
          warmup = 1000,
          iter = 4000,
          control = list(adapt_delta = 0.99)
          )

summary(sa_m2, prob = .997)
```


## 3.3 Model 3: including not directly with contraceptive method associated predictors
```{r}
sa_m3 <- brm(switch ~ contra_satis * hc_dur + sexual_satisfaction +  sex_freq +(1 | CASEID),
          family = bernoulli(),
          data = cccu_SA,
          prior = set_priors,
          file = "models/sa_m3.Rds",
          warmup = 1000,
          iter = 4000,
          control = list(adapt_delta = 0.99))

summary(sa_m3, prob = .997)
```

## 3.4 Model 4: Controlling for observed selection effects
```{r}

sa_m4 <- brm(switch ~ contra_satis * hc_dur + sexual_satisfaction +  sex_freq + AGE + DEGREE_recode + POVRATE + HLTHPROB_recode + MEDPROB_recode + GAPINS_recode +
              TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves + had_baby_between_waves+ Avoid_r + FEELPG_recode +
              rel_dur_factor + (1 | CASEID),
          family = bernoulli(),
          data = cccu_SA,
          prior = set_priors,
          file = "models/sa_m4.Rds",
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99))

summary(sa_m4, prob = .997)
```


