---
title: "12_SubAnalysis_Robust_Models"
output: html_document
date: "2023-02-03"
---
# 1. Load Packages
```{r}
library(brms)
library(marginaleffects)
library(tidyverse)


options(scipen = 999)

set.seed(180823)

set_priors <- c(prior(normal(0, 1), class = b),
                prior(normal(0, 1), class = sd))
```

# 2. Load Data
```{r}
#SA
load("cccu_R1_s.RData")

load("cccu_R2_s.RData")

load("cccu_R3_s.RData")

```


```{r}

cccu_R1_s <- cccu_R1_s %>%
  arrange(CASEID) %>%
  mutate_if(is.factor, droplevels)

cccu_R2_s <- cccu_R2_s %>%
  arrange(CASEID) %>%
  mutate_if(is.factor, droplevels)

cccu_R3_s <- cccu_R3_s %>%
  arrange(CASEID) %>%
  mutate_if(is.factor, droplevels)
```




# 3. Models of Sub Analyses in robustness analyses

## 5.1 Model 2
### R1
```{r}
R1_sa_m2 <- brm(switch ~ contra_satis * hc_dur + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R1_s,
          prior = set_priors,
          file = "models/R1_sa_m2.Rds",
          warmup = 1000,
          iter = 4000,
          control = list(adapt_delta = 0.99))

summary(R1_sa_m2, prob = .997)
```

### R2
```{r}
R2_sa_m2 <- brm(switch ~ contra_satis * hc_dur + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R2_s,
          prior = set_priors,
          file = "models/R2_sa_m2.Rds",
          warmup = 1000,
          iter = 4000,
          control = list(adapt_delta = 0.99))

summary(R2_sa_m2, prob = .997)
```

### R3
```{r}
R3_sa_m2 <- brm(switch ~ contra_satis * hc_dur + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R3_s,
          prior = set_priors,
          file = "models/R3_sa_m2.Rds",
          warmup = 1000,
          iter = 4000,
          control = list(adapt_delta = 0.99))

summary(R3_sa_m2, prob = .997)
```


## 5.2 Model 3
### R1
```{r}
R1_sa_m3 <- brm(switch ~ contra_satis * hc_dur + sexual_satisfaction +  sex_freq +(1 | CASEID),
          family = bernoulli(),
          data = cccu_R1_s,
          prior = set_priors,
          file = "models/R1_sa_m3.Rds",
          warmup = 1000,
          iter = 4000,
          control = list(adapt_delta = 0.99))

summary(R1_sa_m3, prob = .997)
```

### R2
```{r}
R2_sa_m3 <- brm(switch ~ contra_satis * hc_dur + sexual_satisfaction +  sex_freq +(1 | CASEID),
          family = bernoulli(),
          data = cccu_R2_s,
          prior = set_priors,
          file = "models/R2_sa_m3.Rds",
          warmup = 1000,
          iter = 4000,
          control = list(adapt_delta = 0.99))

summary(R2_sa_m3, prob = .997)
```

### R3
```{r}
R3_sa_m3 <- brm(switch ~ contra_satis * hc_dur + sexual_satisfaction +  sex_freq +(1 | CASEID),
          family = bernoulli(),
          data = cccu_R3_s,
          prior = set_priors,
          file = "models/R3_sa_m3.Rds",
          warmup = 1000,
          iter = 4000,
          control = list(adapt_delta = 0.99))

summary(R3_sa_m3, prob = .997)
```


## 5.3 Model 4
### R1
```{r}

R1_sa_m4 <- brm(switch ~ contra_satis * hc_dur + sexual_satisfaction +  sex_freq + AGE + DEGREE_recode + POVRATE + HLTHPROB_recode + MEDPROB_recode + GAPINS_recode +
              TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves + had_baby_between_waves+ Avoid_r + FEELPG_recode +
              rel_dur_factor + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R1_s,
          prior = set_priors,
          file = "models/R1_sa_m4.Rds",
          warmup = 1500,
          iter = 4700,
          control = list(adapt_delta = 0.99))

summary(R1_sa_m4, prob = .997)
```

### R2
```{r}
R2_sa_m4 <- brm(switch ~ contra_satis * hc_dur + sexual_satisfaction +  sex_freq + AGE + DEGREE_recode + POVRATE + HLTHPROB_recode + MEDPROB_recode + GAPINS_recode +
              TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves + had_baby_between_waves+ Avoid_r + FEELPG_recode +
              rel_dur_factor + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R2_s,
          prior = set_priors,
          file = "models/R2_sa_m4.Rds",
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99))

summary(R2_sa_m4, prob = .997)
```

### R3
```{r}
R3_sa_m4 <- brm(switch ~ contra_satis * hc_dur + sexual_satisfaction +  sex_freq + AGE + DEGREE_recode + POVRATE + HLTHPROB_recode + MEDPROB_recode + GAPINS_recode +
              TYPEINS_recode + NKIDS_t1 +  pregnant_between_waves + had_baby_between_waves+ Avoid_r + FEELPG_recode +
              rel_dur_factor + (1 | CASEID),
          family = bernoulli(),
          data = cccu_R3_s,
          prior = set_priors,
          file = "models/R3_sa_m4.Rds",
          warmup = 1500,
          iter = 4500,
          control = list(adapt_delta = 0.99))

summary(R3_sa_m4, prob = .997)
```
