---
title: "13_SubAnalysis_AME"
output: html_document
date: "2023-02-03"
---

# AMEs Subanalysis {.tabset}
## 1. Load Packages
```{r}
library(brms)
library(marginaleffects)
library(tidyverse)



options(scipen = 999)

set.seed(180822)

set_priors <- c(prior(normal(0, 1), class = b),
                prior(normal(0, 1), class = sd))
```

## 2. Load Data
```{r}
load("cccu_SA.RData")

cccu_SA <- cccu_SA %>%
  arrange(CASEID) %>%
  mutate_if(is.factor, droplevels)
```


## 3. Load models of main analysis
```{r}
sa_m2 <- brm(file = "models/sa_m2.Rds")
sa_m3 <- brm(file = "models/sa_m3.Rds")
sa_m4 <- brm(file = "models/sa_m4.Rds")

sa_m3_hc_dur <- brm(file = "models/sa_m3_hc_dur.Rds")
sa_m4_hc_dur <- brm(file = "models/sa_m4_hc_dur.Rds")
```

## Average marginal effects {.tabset}

### m2
```{r}
#average marginal effect
avg_slopes(sa_m2,
           conf_level = .997)
```

### m3
```{r}
#average marginal effect
avg_slopes(sa_m3, 
           conf_level = .997)
```

### m3_hcdur
```{r}
#average marginal effect
avg_slopes(sa_m3_hc_dur,
           conf_level = .997)
```


### m4
```{r}
#average marginal effect
avg_slopes(sa_m4, 
           conf_level = .997) %>%
  print(., nrows = 1000)
```


### m4_hcdur
```{r}
#average marginal effect
avg_slopes(sa_m4_hc_dur, 
           conf_level = .997) %>%
  print(., nrows = 1000)
```
