---
title: "99_check_number_switches"
output: html_document
---
# Library
```{r}
library(formr)
library(tidyverse)
```

# Loading Data
```{r}
load("01_RData/DS0001/37067-0001-Data.rda")
cccu_wave1 = da37067.0001

load("01_RData/DS0002/37067-0002-Data.rda")
cccu_wave2 = da37067.0002

load("01_RData/DS0003/37067-0003-Data.rda")
cccu_wave3 = da37067.0003

load("01_RData/DS0004/37067-0004-Data.rda")
cccu_wave4 = da37067.0004
```

# Select data
```{r}
cccu_wave1 = cccu_wave1 %>% select(CASEID, PILL, PATCH, RING, DEPO, IMPLANT, IUD, CONDOMR,
                                   VASECTOMY, WITHDRAWR, NFPR, SPERMR, NOBARRIER)

cccu_wave2 = cccu_wave2 %>% select(CASEID, PILL, PATCH, RING, DEPO, IMPLANT, IUD, CONDOMR,
                                   VASECTOMY, WITHDRAWR, NFPR, SPERMR, NOBARRIER)

cccu_wave3 = cccu_wave3 %>% select(CASEID, PILL, PATCH, RING, DEPO, IMPLANT, IUD, CONDOMR,
                                   VASECTOMY, WITHDRAWR, NFPR, SPERMR, NOBARRIER)

cccu_wave4 = cccu_wave4 %>% select(CASEID, PILL, PATCH, RING, DEPO, IMPLANT, IUD, CONDOMR,
                                   VASECTOMY, WITHDRAWR, NFPR, SPERMR, NOBARRIER)
```

# HC
```{r}
cccu_wave1 <- cccu_wave1 %>%
  mutate(hc1 = ifelse(PILL %contains% "1"|
                       PATCH %contains% "1" |
                       RING %contains% "1" |
                       DEPO %contains% "1" |
                       IMPLANT %contains% "1", 1,
                      ifelse(IUD %contains% "1", NA,
                             ifelse(CONDOMR %contains% "1"| #actively include non_hc user as 0
                                     VASECTOMY %contains% "1"|
                                     WITHDRAWR %contains% "1" |
                                     NFPR %contains% "1" |
                                     SPERMR %contains% "1" |
                                     NOBARRIER %contains% "1", 0, NA))),
         hc1 = ifelse(PILL %contains% "0" &
                       PATCH %contains% "0" &
                       RING %contains% "0" &
                       DEPO %contains% "0" &
                       IMPLANT %contains% "0" &
                        IUD %contains% "0", 0, hc1))



cccu_wave2 <- cccu_wave2 %>%
  mutate(hc2 = ifelse(PILL %contains% "1"|
                       PATCH %contains% "1" |
                       RING %contains% "1" |
                       DEPO %contains% "1" |
                       IMPLANT %contains% "1", 1,
                      ifelse(IUD %contains% "1", NA,
                             ifelse(CONDOMR %contains% "1"| #actively include non_hc user as 0
                                     VASECTOMY %contains% "1"|
                                     WITHDRAWR %contains% "1" |
                                     NFPR %contains% "1" |
                                     SPERMR %contains% "1" |
                                     NOBARRIER %contains% "1",0, NA))),
         hc2 = ifelse(PILL %contains% "0" &
                       PATCH %contains% "0" &
                       RING %contains% "0" &
                       DEPO %contains% "0" &
                       IMPLANT %contains% "0" &
                        IUD %contains% "0", 0, hc2))

cccu_wave3 <- cccu_wave3 %>%
  mutate(hc3 = ifelse(PILL %contains% "1"|
                       PATCH %contains% "1" |
                       RING %contains% "1" |
                       DEPO %contains% "1" |
                       IMPLANT %contains% "1", 1,
                      ifelse(IUD %contains% "1", NA,
                             ifelse(CONDOMR %contains% "1"| #actively include non_hc user as 0
                                     VASECTOMY %contains% "1"|
                                     WITHDRAWR %contains% "1" |
                                     NFPR %contains% "1" |
                                     SPERMR %contains% "1" |
                                     NOBARRIER %contains% "1", 0, NA))),
         hc3 = ifelse(PILL %contains% "0" &
                       PATCH %contains% "0" &
                       RING %contains% "0" &
                       DEPO %contains% "0" &
                       IMPLANT %contains% "0" &
                        IUD %contains% "0", 0, hc3))

cccu_wave4 <- cccu_wave4 %>%
  mutate(hc4 = ifelse(PILL %contains% "1"|
                       PATCH %contains% "1" |
                       RING %contains% "1" |
                       DEPO %contains% "1" |
                       IMPLANT %contains% "1", 1,
                      ifelse(IUD %contains% "1", NA,
                             ifelse(CONDOMR %contains% "1"| #actively include non_hc user as 0
                                     VASECTOMY %contains% "1"|
                                     WITHDRAWR %contains% "1" |
                                     NFPR %contains% "1" |
                                     SPERMR %contains% "1" |
                                     NOBARRIER %contains% "1", 0, NA))),
         hc4 = ifelse(PILL %contains% "0" &
                       PATCH %contains% "0" &
                       RING %contains% "0" &
                       DEPO %contains% "0" &
                       IMPLANT %contains% "0" &
                        IUD %contains% "0", 0, hc4))
```

# Join
```{r}
data <- left_join(
  left_join(
    left_join(
      cccu_wave1, cccu_wave2, by = "CASEID"),
    cccu_wave3, by = "CASEID"),
  cccu_wave4, by = "CASEID")

data = data %>%
  select(CASEID, starts_with("hc"))
```

# Count
```{r}
# Potential switch between wave 1 and wave 2
crosstabs(~is.na(data$hc1) + is.na(data$hc2)) #2859 potential switches

# Potential Switch between wave 2 and wave 3
crosstabs(~is.na(data$hc2) + is.na(data$hc3)) #2148 potential switches

# Potential Switch between wave 3 and wave 4
crosstabs(~is.na(data$hc3) + is.na(data$hc4)) #1640 potential switches

2859  + 2148   + 1640  #6647 potential switches
```

# Switch
```{r}
data = data %>%
  mutate(switch_1to2 = ifelse(hc1 == hc2, 0, 1),
         switch_2to3 = ifelse(hc2 == hc3, 0, 1),
         switch_3to4 = ifelse(hc3 == hc4, 0, 1))

# Switch between wave 1 and wave 2
sum(data$switch_1to2, na.rm = T) # 372 switches

# Switch between wave 2 and wave 3
sum(data$switch_2to3, na.rm = T) # 236 switches

# Switch between wave 2 and wave 3
sum(data$switch_3to4, na.rm = T) # 184 switches

sum(data$switch_1to2, data$switch_2to3, data$switch_3to4, na.rm = T) #792 switches
```

